### ISSUE TITLE
Cache node_modules for Github builds

### ISSUE THREAD

**Issue by smozely** [batect/batect-sample-typescript#9]
Hi there,

I've been migrating a Typescript/Gatsby to use batect and Github actions (from standard CircleCI)

Using this repo as an example, I'm confused around what the caching is doing, and how I'd cache `node_modules`

I took a fork of this repo, and added --verbose to the `yarn install` and it looks like when github actions runs its download all of the deps each time.

From the name, I was guessing thats what this block is doing 
```
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: .batect/caches
          key: npm-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            npm-
```
... But I don't really understand how by restoring `.batect/caches` it would preserve node_modules, and if that isn't what is supposed to be happening, what is that block supposed to be doing?

Thanks
